default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ticketclick_dev

test:
  <<: *default
  database: ticketclick_test

production:
  <<: *default
  database: ticketclick_production
  username: ticketclick
  password: <%= ENV['TICKETCLICK_DATABASE_PASSWORD'] %>
